### ISSUE TITLE
使用或覆盖了已过时的 API

### ISSUE THREAD

**Issue by NiNi-zhAo** [crossoverJie/blog.toolbox#8]
[WARNING] /Users/huazhang/Dreamer/CODE/blog.toolbox/src/main/java/top/crossoverjie/nows/nows/config/BeanConfig.java: /Users/huazhang/Dreamer/CODE/blog.toolbox/src/main/java/top/crossoverjie/nows/nows/config/BeanConfig.java使用或覆盖了已过时的 API。
[WARNING] /Users/huazhang/Dreamer/CODE/blog.toolbox/src/main/java/top/crossoverjie/nows/nows/config/BeanConfig.java: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
[WARNING] /Users/huazhang/Dreamer/CODE/blog.toolbox/src/main/java/top/crossoverjie/nows/nows/scan/ScannerFile.java: /Users/huazhang/Dreamer/CODE/blog.toolbox/src/main/java/top/crossoverjie/nows/nows/scan/ScannerFile.java使用了未经检查或不安全的操作。
[WARNING] /Users/huazhang/Dreamer/CODE/blog.toolbox/src/main/java/top/crossoverjie/nows/nows/scan/ScannerFile.java: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
[INFO] 4 warnings
[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /Users/huazhang/Dreamer/CODE/blog.toolbox/src/main/java/top/crossoverjie/nows/nows/filter/TotalSumFilterProcessManager.java:[9,24] 找不到符号
  符号:   类 PostConstruct
  位置: 程序包 javax.annotation
[ERROR] /Users/huazhang/Dreamer/CODE/blog.toolbox/src/main/java/top/crossoverjie/nows/nows/filter/TotalSumFilterProcessManager.java:[10,24] 找不到符号
  符号:   类 Resource
  位置: 程序包 javax.annotation
[ERROR] /Users/huazhang/Dreamer/CODE/blog.toolbox/src/main/java/top/crossoverjie/nows/nows/filter/FixPicFilterProcessManager.java:[10,24] 找不到符号
  符号:   类 PostConstruct
  位置: 程序包 javax.annotation
[ERROR] /Users/huazhang/Dreamer/CODE/blog.toolbox/src/main/java/top/crossoverjie/nows/nows/filter/FixPicFilterProcessManager.java:[11,24] 找不到符号
  符号:   类 Resource
  位置: 程序包 javax.annotation
[ERROR] /Users/huazhang/Dreamer/CODE/blog.toolbox/src/main/java/top/crossoverjie/nows/nows/filter/TotalSumFilterProcessManager.java:[27,6] 找不到符号
  符号:   类 Resource
  位置: 类 top.crossoverjie.nows.nows.filter.TotalSumFilterProcessManager
[ERROR] /Users/huazhang/Dreamer/CODE/blog.toolbox/src/main/java/top/crossoverjie/nows/nows/filter/TotalSumFilterProcessManager.java:[30,6] 找不到符号
  符号:   类 Resource
  位置: 类 top.crossoverjie.nows.nows.filter.TotalSumFilterProcessManager
[ERROR] /Users/huazhang/Dreamer/CODE/blog.toolbox/src/main/java/top/crossoverjie/nows/nows/filter/TotalSumFilterProcessManager.java:[36,6] 找不到符号
  符号:   类 PostConstruct
  位置: 类 top.crossoverjie.nows.nows.filter.TotalSumFilterProcessManager
[ERROR] /Users/huazhang/Dreamer/CODE/blog.toolbox/src/main/java/top/crossoverjie/nows/nows/filter/FixPicFilterProcessManager.java:[27,6] 找不到符号
  符号:   类 Resource
  位置: 类 top.crossoverjie.nows.nows.filter.FixPicFilterProcessManager
[ERROR] /Users/huazhang/Dreamer/CODE/blog.toolbox/src/main/java/top/crossoverjie/nows/nows/filter/FixPicFilterProcessManager.java:[30,6] 找不到符号
  符号:   类 Resource
  位置: 类 top.crossoverjie.nows.nows.filter.FixPicFilterProcessManager
[ERROR] /Users/huazhang/Dreamer/CODE/blog.toolbox/src/main/java/top/crossoverjie/nows/nows/filter/FixPicFilterProcessManager.java:[38,6] 找不到符号
  符号:   类 PostConstruct
  位置: 类 top.crossoverjie.nows.nows.filter.FixPicFilterProcessManager
[INFO] 10 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:47 min
[INFO] Finished at: 2019-07-27T10:25:56+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project blog.toolbox: Compilation failure: Compilation failure:
[ERROR] /Users/huazhang/Dreamer/CODE/blog.toolbox/src/main/java/top/crossoverjie/nows/nows/filter/TotalSumFilterProcessManager.java:[9,24] 找不到符号
[ERROR]   符号:   类 PostConstruct
[ERROR]   位置: 程序包 javax.annotation
[ERROR] /Users/huazhang/Dreamer/CODE/blog.toolbox/src/main/java/top/crossoverjie/nows/nows/filter/TotalSumFilterProcessManager.java:[10,24] 找不到符号
[ERROR]   符号:   类 Resource
[ERROR]   位置: 程序包 javax.annotation
[ERROR] /Users/huazhang/Dreamer/CODE/blog.toolbox/src/main/java/top/crossoverjie/nows/nows/filter/FixPicFilterProcessManager.java:[10,24] 找不到符号
[ERROR]   符号:   类 PostConstruct
[ERROR]   位置: 程序包 javax.annotation
[ERROR] /Users/huazhang/Dreamer/CODE/blog.toolbox/src/main/java/top/crossoverjie/nows/nows/filter/FixPicFilterProcessManager.java:[11,24] 找不到符号
[ERROR]   符号:   类 Resource
[ERROR]   位置: 程序包 javax.annotation
[ERROR] /Users/huazhang/Dreamer/CODE/blog.toolbox/src/main/java/top/crossoverjie/nows/nows/filter/TotalSumFilterProcessManager.java:[27,6] 找不到符号
[ERROR]   符号:   类 Resource
[ERROR]   位置: 类 top.crossoverjie.nows.nows.filter.TotalSumFilterProcessManager
[ERROR] /Users/huazhang/Dreamer/CODE/blog.toolbox/src/main/java/top/crossoverjie/nows/nows/filter/TotalSumFilterProcessManager.java:[30,6] 找不到符号
[ERROR]   符号:   类 Resource
[ERROR]   位置: 类 top.crossoverjie.nows.nows.filter.TotalSumFilterProcessManager
[ERROR] /Users/huazhang/Dreamer/CODE/blog.toolbox/src/main/java/top/crossoverjie/nows/nows/filter/TotalSumFilterProcessManager.java:[36,6] 找不到符号
[ERROR]   符号:   类 PostConstruct
[ERROR]   位置: 类 top.crossoverjie.nows.nows.filter.TotalSumFilterProcessManager
[ERROR] /Users/huazhang/Dreamer/CODE/blog.toolbox/src/main/java/top/crossoverjie/nows/nows/filter/FixPicFilterProcessManager.java:[27,6] 找不到符号
[ERROR]   符号:   类 Resource
[ERROR]   位置: 类 top.crossoverjie.nows.nows.filter.FixPicFilterProcessManager
[ERROR] /Users/huazhang/Dreamer/CODE/blog.toolbox/src/main/java/top/crossoverjie/nows/nows/filter/FixPicFilterProcessManager.java:[30,6] 找不到符号
[ERROR]   符号:   类 Resource
[ERROR]   位置: 类 top.crossoverjie.nows.nows.filter.FixPicFilterProcessManager
[ERROR] /Users/huazhang/Dreamer/CODE/blog.toolbox/src/main/java/top/crossoverjie/nows/nows/filter/FixPicFilterProcessManager.java:[38,6] 找不到符号
[ERROR]   符号:   类 PostConstruct
[ERROR]   位置: 类 top.crossoverjie.nows.nows.filter.FixPicFilterProcessManager
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by crossoverJie** [comment]
`mvn clean package  -Dmaven.test.skip=true`

试试，我这里没有问题，或者可以直接使用 `release` 包。

![image](https://user-images.githubusercontent.com/15684156/61989335-705cf500-b060-11e9-87ed-71e9645a7551.png)
